name: musickit
description: Apple Musickit support
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  plugin:
    platforms:
      android: 
        package: com.zivost.musickit
        pluginClass: MusickitPlugin
      ios:
        pluginClass: MusickitPlugin
